[package]
name = "fibnacci"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5.3"
rust-gmp = "0.5.0"

[profile.release]
panic = "abort"
strip = true
codegen-units = 1
lto = true

