# Origin config by @Kilerd

name: Build Release

on:
  push:
    branches: [ master ]

jobs:
  release:
    name: Pre-Release on ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        platform: [linux_glibc-x86_64, linux_musl-x86_64]
        include:

          - platform: linux_glibc-x86_64
            target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            bin: fibonacci
            
    steps:
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          target: ${{ matrix.target }}
          toolchain: nightly
          override: true

      - name: Checkout code
        uses: actions/checkout@v1
      
      - name: Install dependencies
        run: |
          sudo apt-get update 
          sudo apt-get upgrade
          sudo apt-get install libgmp-dev pkg-config


      - name: Run code build
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Prepare assets
        shell: bash
        run: |
          mv target/${{ matrix.target }}/release/${{ matrix.bin }} .
          tar -cvf ${{ matrix.target }}.tar LICENSE ${{ matrix.bin }}
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.target }}.tar
          tag_name: v0.4.1
          prerelease: true

